import type { Config } from 'tailwindcss';

const config: Config = {
	darkMode: 'class',
	content: [
		'./pages/**/*.{js,ts,jsx,tsx,mdx}',
		'./components/**/*.{js,ts,jsx,tsx,mdx}',
		'./app/**/*.{js,ts,jsx,tsx,mdx}',
		'./src/**/*.{js,ts,jsx,tsx,mdx}',
		'*.{js,ts,jsx,tsx,mdx}',
	],
	theme: {
		extend: {
			colors: {
				/* --- Brand palette --- */
				primary: {
					/* Muted Teal — main CTAs, coffee bean text on top */
					50: '#f0f7f5',
					100: '#d6ecea',
					200: '#addbd7',
					300: '#82c6c0',
					400: '#7aafa7',
					500: '#5d9990',
					600: '#477871',
					700: '#355a55',
					800: '#233c38',
					900: '#121f1d',
					DEFAULT: '#7aafa7',
					foreground: '#1b0e13',
				},
				'coffee-bean': {
					/* Deep dark — sidebar, body text, labels */
					50: '#f5eef1',
					100: '#e8d5dc',
					200: '#cca9b8',
					300: '#ac7c95',
					400: '#875674',
					500: '#613452',
					600: '#451f3b',
					700: '#2e1224',
					800: '#1b0e13',
					900: '#0d0709',
					DEFAULT: '#1b0e13',
				},
				'burnt-peach': {
					/* Warm peach — expenses, accent */
					50: '#fef5f1',
					100: '#fde2d5',
					200: '#f9c3a7',
					300: '#f3a07a',
					400: '#e08462',
					500: '#cb7352',
					600: '#aa5c3e',
					700: '#84462e',
					800: '#5c301f',
					900: '#381d12',
					DEFAULT: '#cb7352',
				},
				'berry-crush': {
					/* Deep pink — destructive, errors, delete, cancel */
					50: '#fdf0f4',
					100: '#f9d4e2',
					200: '#f1a9c4',
					300: '#e07d9f',
					400: '#c95e7f',
					500: '#aa4465',
					600: '#8d3352',
					700: '#6f2440',
					800: '#50172e',
					900: '#330d1d',
					DEFAULT: '#aa4465',
				},
				'ash-grey': {
					/* Soft teal-grey — muted surfaces, borders */
					50: '#f0f6f6',
					100: '#daeced',
					200: '#b5d9da',
					300: '#9db9b8',
					400: '#7da09f',
					500: '#5e8788',
					600: '#496b6c',
					700: '#375052',
					800: '#263638',
					900: '#151e1f',
					DEFAULT: '#9db9b8',
				},
				/* --- shadcn CSS-var tokens (do not rename these) --- */
				background: 'hsl(var(--background))',
				foreground: 'hsl(var(--foreground))',
				card: {
					DEFAULT: 'hsl(var(--card))',
					foreground: 'hsl(var(--card-foreground))',
				},
				popover: {
					DEFAULT: 'hsl(var(--popover))',
					foreground: 'hsl(var(--popover-foreground))',
				},
				secondary: {
					DEFAULT: 'hsl(var(--secondary))',
					foreground: 'hsl(var(--secondary-foreground))',
				},
				muted: {
					DEFAULT: 'hsl(var(--muted))',
					foreground: 'hsl(var(--muted-foreground))',
				},
				accent: {
					DEFAULT: 'hsl(var(--accent))',
					foreground: 'hsl(var(--accent-foreground))',
				},
				destructive: {
					DEFAULT: 'hsl(var(--destructive))',
					foreground: 'hsl(var(--destructive-foreground))',
				},
				border: 'hsl(var(--border))',
				input: 'hsl(var(--input))',
				ring: 'hsl(var(--ring))',
				chart: {
					'1': 'hsl(var(--chart-1))',
					'2': 'hsl(var(--chart-2))',
					'3': 'hsl(var(--chart-3))',
					'4': 'hsl(var(--chart-4))',
					'5': 'hsl(var(--chart-5))',
				},
				sidebar: {
					DEFAULT: 'hsl(var(--sidebar-background))',
					foreground: 'hsl(var(--sidebar-foreground))',
					primary: 'hsl(var(--sidebar-primary))',
					'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
					accent: 'hsl(var(--sidebar-accent))',
					'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
					border: 'hsl(var(--sidebar-border))',
					ring: 'hsl(var(--sidebar-ring))',
				},
			},
			borderRadius: {
				lg: 'var(--radius)',
				md: 'calc(var(--radius) - 2px)',
				sm: 'calc(var(--radius) - 4px)',
			},
			fontFamily: {
				sans: ['var(--font-sans)', 'ui-sans-serif', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
				mono: ['var(--font-mono)', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
			},
		},
	},
	safelist: [
			"bg-primary-400",
			"bg-primary-500",
			"bg-coffee-bean-800",
			"bg-ash-grey-300",
			"bg-ash-grey-500",
			"bg-burnt-peach-500",
			"bg-burnt-peach-600",
			"bg-berry-crush-500",
			"bg-berry-crush-600",
			"bg-orange-500",
			"bg-green-500",
			"bg-blue-500",
			"bg-purple-500",
			"bg-red-500",
			"bg-yellow-500",
			"bg-pink-500",
			"bg-indigo-500",
			"bg-gray-500",
			"bg-cyan-500",
			"bg-emerald-500",
			"bg-violet-500",
			"bg-teal-500",
			"bg-lime-500",
			"bg-amber-500",
			"bg-rose-500",
			"bg-sky-500",
			"bg-fuchsia-500",
			"bg-slate-500",
			"bg-stone-500",
			// portfolio project gradients (lib/portfolio/projects.ts → appScreenColor)
			{
				pattern:
					/^(from|to)-(teal|cyan|sky|blue|orange|red|green|emerald|amber|fuchsia|purple|indigo|violet|pink|rose|zinc)-(500|600|700)$/,
			},
			"to-black",
	],
	plugins: [require('tailwindcss-animate')],
};

export default config;
