import {
  Utensils,
  ShoppingCart,
  Car,
  Home,
  Gamepad2,
  Zap,
  Gift,
  Sparkles,
  Briefcase,
  Plane,
  DollarSign,
  Coffee,
  Heart,
  Music,
  Camera,
  Book,
  Dumbbell,
  Palette,
  Wrench,
  Smartphone,
  Laptop,
  Settings,
  Plus,
  Edit,
  Trash2,
  X,
} from "lucide-react"
import type { LucideIcon } from "lucide-react"

export const availableIcons: { id: string; name: string; icon: LucideIcon }[] = [
  { id: "utensils", name: "Comida", icon: Utensils },
  { id: "shopping-cart", name: "Compras", icon: ShoppingCart },
  { id: "car", name: "Transporte", icon: Car },
  { id: "home", name: "Hogar", icon: Home },
  { id: "gamepad", name: "Juegos", icon: Gamepad2 },
  { id: "zap", name: "Servicios", icon: Zap },
  { id: "gift", name: "Regalos", icon: Gift },
  { id: "sparkles", name: "Belleza", icon: Sparkles },
  { id: "briefcase", name: "Trabajo", icon: Briefcase },
  { id: "plane", name: "Viajes", icon: Plane },
  { id: "dollar", name: "Ingreso", icon: DollarSign },
  { id: "coffee", name: "Café", icon: Coffee },
  { id: "heart", name: "Salud", icon: Heart },
  { id: "music", name: "Música", icon: Music },
  { id: "camera", name: "Fotos", icon: Camera },
  { id: "book", name: "Educación", icon: Book },
  { id: "dumbbell", name: "Ejercicio", icon: Dumbbell },
  { id: "palette", name: "Arte", icon: Palette },
  { id: "wrench", name: "Herramientas", icon: Wrench },
  { id: "smartphone", name: "Teléfono", icon: Smartphone },
  { id: "laptop", name: "Tecnología", icon: Laptop },
]

export const availableColors = [
  { id: "orange-500", class: "bg-orange-500", name: "Naranja" },
  { id: "green-500", class: "bg-green-500", name: "Verde" },
  { id: "blue-500", class: "bg-blue-500", name: "Azul" },
  { id: "purple-500", class: "bg-purple-500", name: "Morado" },
  { id: "red-500", class: "bg-red-500", name: "Rojo" },
  { id: "yellow-500", class: "bg-yellow-500", name: "Amarillo" },
  { id: "pink-500", class: "bg-pink-500", name: "Rosa" },
  { id: "indigo-500", class: "bg-indigo-500", name: "Índigo" },
  { id: "gray-500", class: "bg-gray-500", name: "Gris" },
  { id: "cyan-500", class: "bg-cyan-500", name: "Cian" },
  { id: "emerald-500", class: "bg-emerald-500", name: "Esmeralda" },
  { id: "violet-500", class: "bg-violet-500", name: "Violeta" },
]


export const iconComponents = {  Utensils,
  ShoppingCart,
  Car,
  Home,
  Gamepad2,
  Zap,
  Gift,
  Sparkles,
  Briefcase,
  Plane,
  DollarSign,
  Coffee,
  Heart,
  Music,
  Camera,
  Book,
  Dumbbell,
  Palette,
  Wrench,
  Smartphone,
  Laptop,
  Settings,
  Plus,
  Edit,
  Trash2,
  X, }
